### ISSUE TITLE
Ordenação por Valor de Proposta

### ISSUE THREAD

**Issue by mateuswetah** [Lafaiet/salicapi#10]
Aparentemente a ordenação por valor_proposta na consulta pro Projetos não está funcionando (retorna _Internal Error_, _Code 13_, _Something is broken_, após alguns segundos de processamento.

Ex.: [hmg.api.salic.cultura.gov.br/beta/projetos/?limit=10&offset=0&sort=valor_proposta:desc](hmg.api.salic.cultura.gov.br/beta/projetos/?limit=10&offset=0&sort=valor_proposta:desc)

**Comment by Lafaiet** [comment]
Erro no uso da função interna que mapeia "isnull" do sqlserver ocasionando arithmetic overflow. Corrigido.
