### ISSUE TITLE
Permitir escolha de formato a partir de query na URL

### ISSUE THREAD

**Issue by mateuswetah** [Lafaiet/salicapi#12]
Apesar de já ser possível baixarmos os dados em JSON, XML e CSV, a escolha deste formato é passada pelo _header_ da requisição, o que restringe as possibilidades de acesso à operações em backend. Se um cliente deseja fazer uma consulta via CSV, por exemplo, ele não tem como pedir somente via URL. 

Como já foi discutido, isso é uma questão de padrão de projeto para a API, mas considero pertinente termos uma _query_ do tipo **"format"** para fazer essa requisição de modo mais acessível ao usuário, facilitando o compartilhamento de dados consultados em outros formatos além do padrão.

**Comment by Lafaiet** [comment]
Done
