### ISSUE TITLE
Colocar nome e cabeçalho no arquivo CSV exportado

### ISSUE THREAD

**Issue by leogermani** [Lafaiet/salicapi#15]
- [ ] Colocar cabeçalho de arquivo CSV, assim o navegador sabe o que é e pode sugerir abrir numa planilha

- [ ] Colocar um nome amigável para o arquivo, com a extensao .csv

Sugestões de nomes. (acho que podemos discutir aqui um pouco:

prefixo - acho que todos os arquivos poderiam começar com versalic- ou só salic-

entidade - em seguida poderia vir o nome da entidade exportada: projetos, fornecedores, etc.

Por último poderia vir alguma coisa que identificasse aquela consulta... Ainda mais quando tiver que fazer vários downloads para uma consulta com mais de 100 itens, os arquivos tem q ter nome diferente, se não vai ser ruim.

Propostas

1. Montar um hash md5 jogando todos os parametros da busca, incluindo offset e limit. Isso é legal pq daí dá pra guardar num cache esse csv se quiser.

2. colocar só o offset e limit

Exemplo na opção 1:

`versalic-projetos-202cb962ac59075b964b07152d234b70.csv`

ou com um hash resumido

`versalic-projetos-d234b70.csv`

Na opção 2

`versalic-projetos-1-100.csv`

Ou ainda podemos combinar as duas coisas. O offset no nome do arquivo é bom para o usuário:

`versalic-projetos-1-100-d234b70.csv`

**Comment by Lafaiet** [comment]
Função implementada tomando como base **opção 1**.

**Comment by mateuswetah** [comment]
Eu sou do time opção dois hehehe. Ou a mescla das duas, claro. 

Porque se o cara baixa cinco planilhas e abre no navegador de arquivos dele, dependendo da ordenação que estiver lá já não está claro quem vem primeiro. Antes da hash, ainda havia casos como o do Google Chrome que colocaria um (1), (2), etc logo após o nome caso fosse igual. Agora nem isso.

Sei que não é obrigação do lado da API, mas acho que é um detalhe simples que ajuda.

**Comment by Lafaiet** [comment]
Em geral o gerenciador de downloads já ordena os ítens baixados, certo? Por hora vou manter o que foi feito.
