### ISSUE TITLE
Consultas a Fornecedor filtradas por PRONAC retornam Internal Error

### ISSUE THREAD

**Issue by mateuswetah** [Lafaiet/salicapi#17]
Exemplo: [http://hmg.api.salic.cultura.gov.br/beta/fornecedores/?PRONAC=095056](http://hmg.api.salic.cultura.gov.br/beta/fornecedores/?PRONAC=095056)

**Comment by mateuswetah** [comment]
Poderíamos ter essa questão como prioridade? Andei checando com outros PRONACs, realmente não é um caso específico, não funciona nenhum :P

**Comment by Lafaiet** [comment]
Corrigido
