### ISSUE TITLE
Alterar endereço base dos arquivos anexos

### ISSUE THREAD

**Issue by nitaibezerra** [Lafaiet/salicapi#18]
Na construção dos links para download de arquivos anexos, não usar o endereço com novosalic.cultura.gov.br, e sim salic.cultura.gov.br

Não funciona: http://novosalic.cultura.gov.br/verprojetos/abrir-documentos-anexados?id=170523&tipo=2&idPronac=208183

Funciona: http://salic.cultura.gov.br/verprojetos/abrir-documentos-anexados?id=170523&tipo=2&idPronac=208183

**Comment by Lafaiet** [comment]
Corrigo. Trata-se de parâmetro a ser definido no arquivo de configuração: **SALIC_BASE_URL**. Caso venha a ser alterado novamente, é imprescindível a reconfiguração para direcionamento correto desses anexos.
