### ISSUE TITLE
Algumas páginas de Projeto retornando 502 Bad Gateway

### ISSUE THREAD

**Issue by mateuswetah** [Lafaiet/salicapi#23]
Já foi comentado antes, mas só para deixarmos registrado...
Alguns projetos são listados na página de consulta, mas quando acessamos a consulta do Projeto em si, é retornado **Erro 502 Bad Gateway**.

Por exemplo: [http://hmg.api.salic.cultura.gov.br/beta/projetos/123394/](http://hmg.api.salic.cultura.gov.br/beta/projetos/123394/)

**Comment by Lafaiet** [comment]
Erro consistia em division by zero ao calcular perc_executado e perc_a_executado. Corrigido.
