### ISSUE TITLE
Prover opção de 'limit' e 'offset' para Produtos e Doações

### ISSUE THREAD

**Issue by mateuswetah** [Lafaiet/salicapi#4]
Não sei se é contra o padrão que está sendo seguido, mas acredito que as consultas **/fornecedores/{id}/produtos** e **/incentivadores/{id}/doacoes** também deveriam permitir o uso de queries '_offset_' e '_limit_', além de retornar campos '_count_' e 'total' da mesma forma que é feito nos recursos tipo listagem. Só a consulta de [doações pelo Banco do Brasil](http://hmg.api.salic.cultura.gov.br/beta/incentivadores/1151e24b23a1146adb06ec7028492b89a1517b3b2ab3f0b826049d490056/doacoes/) por exemplo, já nos retorna mais de 100 itens!

**Comment by Lafaiet** [comment]
Adicionado recurso de paginação para doações.

**Comment by Lafaiet** [comment]
Adicionado recurso de paginação para produtos.
