### ISSUE TITLE
Especificar padrão de ordenação na Documentação.

### ISSUE THREAD

**Issue by mateuswetah** [Lafaiet/salicapi#5]
Notei que não há na documentação, lugar algum indicando qual a ordenação padrão pela qual os itens são apresentados em uma consulta caso a query 'sort' não tenha sido passada. Para projetos, por exemplo, creio que é PRONAC, não tenho certeza... seria com estar lá da mesma maneira que 'offset' e 'limit' já estão.

**Comment by Lafaiet** [comment]
Done.
