### ISSUE TITLE
Campos com conteúdo não especificado no Model Scheme da documentação.

### ISSUE THREAD

**Issue by mateuswetah** [Lafaiet/salicapi#6]
Há alguns campos no Model Scheme de Projeto que estão sem descrição de conteúdo. Podemos inferir o que há neles pelo resultado da consulta, mas nem sempre estes vem com valores dentro. Os que eu notei até o momento:

- [ ] relatorio_fisico;
- [ ] relacao_pagamentos;
- [ ] readequacoes.pedidos;
- [ ] readequacoes.pareceres;

**Comment by Lafaiet** [comment]
Documentação corrigida. Objetos descritos com seus respectivos campos.
