### ISSUE TITLE
Item de relacoes_pagamentos poderia ter link para Fornecedor

### ISSUE THREAD

**Issue by mateuswetah** [Lafaiet/salicapi#9]
De maneira similar ao caso dos Incentivadores no vetor doacoes, poderíamos ter um link para o Fornecedor em cada item  do vetor relacoes_pagamentos  na consulta ao Projeto. 

Isso aumentaria as possibilidades de navegação, já que no momento temos os dados do Fornecedor, mas precisamos fazer a consulta filtrada pelo CGCCPF ou nome do mesmo para chegar até sua página.

**Comment by Lafaiet** [comment]
Indispensável, visto que a busca por cgccpf fica inviável no caso de se tratar de pessoa física por conta da máscara aplicada nesses casos.

**Comment by Lafaiet** [comment]
DONE
